const LESSON_ID_BY_LABEL: Record<string, string> = {
  regime: "regime",
  "market regime": "regime",
  "gamma environment": "regime",
  "dealer bias": "dealer-bias",
  confiança: "confidence",
  confidence: "confidence",
  "confiança do regime": "confidence",
  risco: "risk",
  "gex total": "gex-total",
  "net gex": "gex-total",
  "call wall": "call-wall",
  "put wall": "put-wall",
  "gamma flip": "gamma-flip",
  "gamma magnet": "gamma-magnet",
  "maior net gex": "largest-net-gex",
  "score institucional": "institutional-score",
  intensidade: "intensity",
  "risco rompimento": "breakout-risk",
  rompimento: "breakout-risk",
  "risco reversão": "reversal-risk",
  reversão: "reversal-risk",
  "call oi total": "call-oi-total",
  "put oi total": "put-oi-total",
  "open interest total": "open-interest-total",
  "oi novo": "new-open-interest",
  "net oi": "net-oi",
  "maior concentração": "largest-concentration",
  concentração: "largest-concentration",
  "oi concentration score": "oi-concentration-score",
  "oi score": "oi-concentration-score",
  "iv ponderada": "weighted-iv",
  "call iv": "call-iv",
  "put iv": "put-iv",
  "iv skew": "iv-skew",
  "volatility smile": "iv-skew",
  "expected move": "expected-move",
  "call gex": "call-gex",
  "put gex": "put-gex",
  "gex bruto": "gross-gex",
  "dealer pressure": "dealer-pressure",
  strikes: "strikes",
};

export function getAcademyLessonIdForIndicator(
  indicatorLabel: string,
): string | null {
  return LESSON_ID_BY_LABEL[indicatorLabel.trim().toLowerCase()] ?? null;
}
